name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # meta
          API_BASE_URL: https://wakatime.com/api
          # content
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_UPDATED_DATE: true
          UPDATED_DATE_FORMAT: "%d/%m/%Y"
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
          SHOW_COMMIT: true
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_SHORT_INFO: true
          SYMBOL_VERSION: 1
          SHOW_LOC_CHART: true
          IGNORED_LANGUAGEs: HTML TEXT TXT MARKDOWN
          # commit
          COMMIT_MESSAGE: Updated Waka Data
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMIT_BY_ME: true
